//! Snouty Tufty build.
//!
//!   zig build                     firmware into zig-out/firmware/
//!   zig build -Dcart=snouty-run   pick the cart the Tufty OS embeds
//!   zig build -Dscale=crop        cart scale mode: fit, crop, native (default per
//!                                 cart: fit for snouty-run, crop for demosnout)
//!   zig build test                host unit tests
//!
//! Firmware outputs (ELF + UF2, family RP2350_ARM_S, all below 0x10200000):
//!   snouty-tufty-hello       M0 bring-up test screen, clk_sys 250 MHz
//!   snouty-tufty-hello-150   the same at 150 MHz (fallback for the clock path)
//!   snouty-tufty-<cart>      M1 Tufty OS running one SYCL RAM cart, 250 MHz
//!
//! The cart is built, unmodified, by the snouty-badge submodule's own
//! build.zig (a path dependency), exactly as for the SYCL badge; we take its
//! ELF, objcopy the loadable bytes and embed them.
//!
//! Keep this file free of file-existence or environment branching: this Zig
//! caches the configure-phase graph by build files + options only.
const std = @import("std");
const Build = std.Build;

const microzig = @import("microzig");

const MicroBuild = microzig.MicroBuild(.{
    .rp2xxx = true,
});

/// Carts the Tufty OS knows. `name` is the -Dcart name (the directory under
/// snouty-badge/carts/), `binary` the firmware name its build installs,
/// `scale` the cart's default scale mode (-Dscale overrides it).
const Cart = struct { name: []const u8, binary: []const u8, scale: Scale = .fit };
const carts = [_]Cart{
    .{ .name = "snouty-run", .binary = "snouty" },
    .{ .name = "demosnout", .binary = "demosnout", .scale = .crop },
    .{ .name = "snouty-bugs", .binary = "snouty-bugs" },
};

const Scale = enum { fit, crop, native };

pub fn build(b: *Build) void {
    const cart_name = b.option([]const u8, "cart", "Cart for the Tufty OS image (default snouty-run)") orelse "snouty-run";
    const scale_option = b.option(Scale, "scale", "Cart scale mode: fit (128->240 rows), crop (2x, drop 4 rows top and bottom), native (1:1 centred). Default: per cart (fit unless the carts table says otherwise)");

    const mz_dep = b.dependency("microzig", .{});
    const mb = MicroBuild.init(b, mz_dep) orelse return;

    const tufty_target = tufty_microzig_target(mb, b);

    // The SYCL OS 8x8 font, shared through the snouty-badge submodule.
    const font_mod = b.createModule(.{
        .root_source_file = b.path("snouty-badge/sycl-badge/src/font.zig"),
    });

    add_hello(b, mb, tufty_target, font_mod, "snouty-tufty-hello", 250);
    add_hello(b, mb, tufty_target, font_mod, "snouty-tufty-hello-150", 150);

    const cart = for (carts) |c| {
        if (std.mem.eql(u8, c.name, cart_name)) break c;
    } else std.debug.panic("-Dcart: unknown cart '{s}' (known: snouty-run, demosnout)", .{cart_name});
    add_cart_host(b, mb, tufty_target, cart, scale_option orelse cart.scale);

    // Host tests: the pure pixel / pattern / ABI code, no microzig.
    const unit_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/test.zig"),
            .target = b.graph.host,
            .optimize = .Debug,
            .imports = &.{
                .{ .name = "font", .module = font_mod },
            },
        }),
    });
    const run_unit_tests = b.addRunArtifact(unit_tests);
    const test_step = b.step("test", "Run host unit tests");
    test_step.dependOn(&run_unit_tests.step);
}

/// One hello firmware at a given clk_sys (MHz).
fn add_hello(
    b: *Build,
    mb: *MicroBuild,
    target: *microzig.Target,
    font_mod: *Build.Module,
    name: []const u8,
    sys_mhz: u32,
) void {
    const options = b.addOptions();
    options.addOption(u32, "sys_mhz", sys_mhz);

    const fw = mb.add_firmware(.{
        .name = name,
        .target = target,
        .optimize = .ReleaseSmall,
        .root_source_file = b.path("src/hello.zig"),
        .imports = &.{
            .{ .name = "font", .module = font_mod },
            .{ .name = "build_options", .module = options.createModule() },
        },
    });
    install(mb, fw);
}

/// The Tufty OS with one cart embedded.
fn add_cart_host(b: *Build, mb: *MicroBuild, target: *microzig.Target, cart: Cart, scale: Scale) void {
    // Configure the monorepo for just this cart, RAM mode, default options.
    const badge = b.dependency("snouty_badge", .{ .cart = cart.name });
    const cart_elf = installed_file(badge.builder, b.fmt("{s}.elf", .{cart.binary}));

    // The cart's loadable bytes, from its link address 0x20035100 up to the
    // end of .data (BSS is NOLOAD and is zeroed at launch).
    const cart_bin = b.addObjCopy(cart_elf, .{ .basename = "cart.bin", .format = .binary });
    const image_files = b.addWriteFiles();
    _ = image_files.addCopyFile(cart_bin.getOutput(), "cart.bin");
    const image_src = image_files.add("cart_image.zig",
        \\//! Generated by build.zig: the embedded cart image.
        \\pub const bytes: []const u8 = @embedFile("cart.bin");
        \\
    );

    const options = b.addOptions();
    options.addOption(u32, "sys_mhz", 250);
    options.addOption([]const u8, "cart_name", cart.name);
    options.addOption([]const u8, "scale", @tagName(scale));

    const fw = mb.add_firmware(.{
        .name = b.fmt("snouty-tufty-{s}", .{cart.name}),
        .target = target,
        .optimize = .ReleaseSmall,
        .root_source_file = b.path("src/cart_host.zig"),
        .imports = &.{
            .{ .name = "build_options", .module = options.createModule() },
            .{ .name = "cart_image", .module = b.createModule(.{ .root_source_file = image_src }) },
        },
    });
    install(mb, fw);

    // Also install the cart ELF and image next to it, for inspection.
    b.getInstallStep().dependOn(&b.addInstallFileWithDir(cart_elf, .{ .custom = "firmware/cart" }, b.fmt("{s}.elf", .{cart.binary})).step);
    b.getInstallStep().dependOn(&b.addInstallFileWithDir(cart_bin.getOutput(), .{ .custom = "firmware/cart" }, b.fmt("{s}.bin", .{cart.binary})).step);
}

/// The source of a file a dependency's build installs under
/// `<prefix>/firmware/<basename>` (microzig's install_firmware). This walks
/// the dependency's configured step graph; it never looks at the disk.
fn installed_file(dep_b: *Build, basename: []const u8) Build.LazyPath {
    for (dep_b.getInstallStep().dependencies.items) |step| {
        const install_file = step.cast(Build.Step.InstallFile) orelse continue;
        const in_firmware = switch (install_file.dir) {
            .custom => |dir| std.mem.eql(u8, dir, "firmware"),
            else => false,
        };
        if (in_firmware and std.mem.eql(u8, install_file.dest_rel_path, basename)) return install_file.source;
    }
    std.debug.panic("snouty-badge build installs no firmware/{s}", .{basename});
}

fn install(mb: *MicroBuild, fw: *MicroBuild.Firmware) void {
    mb.install_firmware(fw, .{ .format = .elf });
    mb.install_firmware(fw, .{ .format = .{ .uf2 = .{ .family_id = .RP2350_ARM_S } } });
}

/// Tufty 2350 target: the Pico 2 (RP2350, Arm) target with our board file
/// and two memory cuts the linker then enforces:
///   - flash 2 MB: 0x10000000..0x10200000 is the stock MicroPython firmware
///     slot; the badge's ROMFS and FAT filesystem start at 0x10200000 and
///     must survive our flash.
///   - main RAM 128 KB: 0x20020000..0x20080000 belongs to the cart (SYCL
///     cart ABI: IPC block, cart image at 0x20035100, cart stack at the top).
///     The OS's data, BSS and stack stay below 0x20020000.
fn tufty_microzig_target(mb: *MicroBuild, b: *Build) *microzig.Target {
    const base_target = mb.ports.rp2xxx.boards.raspberrypi.pico2_arm;

    var chip = base_target.chip;
    chip.memory_regions = &.{
        .{ .tag = .flash, .offset = 0x10000000, .length = 2 * 1024 * 1024, .access = .rx },
        .{ .tag = .ram, .offset = 0x20000000, .length = 128 * 1024, .access = .rwx },
        .{ .tag = .ram, .offset = 0x20080000, .length = 4 * 1024, .access = .rwx },
        .{ .tag = .ram, .offset = 0x20081000, .length = 4 * 1024, .access = .rwx },
    };

    return base_target.derive(.{
        .chip = chip,
        .board = .{
            .name = "Pimoroni Tufty 2350",
            .url = "https://shop.pimoroni.com/products/tufty-2350",
            .root_source_file = b.path("src/board.zig"),
        },
    });
}
