//! Writes the `xip_meta` module of an XIP cart build to stdout (run by
//! build.zig): where the UF2 puts the cart image and the drive, their
//! lengths and CRC32s. The Tufty OS checks both against flash at boot, so a
//! UF2 that only partly landed shows a fail screen instead of running.
//!
//!   xip_meta <image addr> <image.bin> [<drive addr> <drive.img>]
//!
//! Without a drive, `drive_len` is 0 and the OS checks only the image.
const std = @import("std");

var io_mem: std.Io.Threaded = .init_single_threaded;
const io = io_mem.io();

fn die(comptime fmt: []const u8, args: anytype) noreturn {
    std.debug.print("\nerror: xip_meta: " ++ fmt ++ "\n\n", args);
    std.process.exit(1);
}

pub fn main(init: std.process.Init.Minimal) !void {
    const gpa = std.heap.page_allocator;
    var args = try init.args.iterateAllocator(gpa);
    defer args.deinit();
    _ = args.next();
    const cwd = std.Io.Dir.cwd();

    var addrs: [2]u32 = @splat(0);
    var lens: [2]u32 = @splat(0);
    var crcs: [2]u32 = @splat(0);
    for (0..2) |i| {
        const addr_s = args.next() orelse if (i == 1) break else die("usage: xip_meta <image addr> <image.bin> [<drive addr> <drive.img>]", .{});
        addrs[i] = std.fmt.parseInt(u32, addr_s, 0) catch die("bad address {s}", .{addr_s});
        const path = args.next() orelse die("missing file after {s}", .{addr_s});
        const bytes = cwd.readFileAlloc(io, path, gpa, .limited(16 << 20)) catch |e| die("cannot read {s}: {s}", .{ path, @errorName(e) });
        lens[i] = @intCast(bytes.len);
        crcs[i] = std.hash.Crc32.hash(bytes);
    }

    var out_buf: [1024]u8 = undefined;
    var ow = std.Io.File.stdout().writer(io, &out_buf);
    const w = &ow.interface;
    try w.print(
        \\//! Generated by tools/xip_meta.zig: what this firmware's UF2 writes
        \\//! besides the OS (build.zig add_os), checked at boot.
        \\pub const present = true;
        \\pub const image_addr: u32 = 0x{X:0>8};
        \\pub const image_len: u32 = {d};
        \\pub const image_crc: u32 = 0x{X:0>8};
        \\pub const drive_addr: u32 = 0x{X:0>8};
        \\pub const drive_len: u32 = {d};
        \\pub const drive_crc: u32 = 0x{X:0>8};
        \\
    , .{ addrs[0], lens[0], crcs[0], addrs[1], lens[1], crcs[1] });
    try w.flush();
}
